version: "3.7"
services:
  mysql:
    image: mysql:latest
    container_name: schema-test-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 127.0.0.1:43306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: test_db
      MYSQL_USER: mysql_test_user
      MYSQL_PASSWORD: password

  postgres:
    image: postgres:latest
    container_name: schema-test-postgres
    restart: always
    ports:
      - 127.0.0.1:45432:5432
    environment:
        POSTGRES_HOST_AUTH_METHOD: trust
